### ISSUE TITLE
How can i retain the entire commit history?

### ISSUE THREAD

**Issue by blu3sh0rk** [aflchurn/aflchurn#1]
Hello!
         Can you tell me how to retain the entire commit history?
![image](https://user-images.githubusercontent.com/49183837/145707401-8301c0c4-16c9-470b-8af4-bd80a2fbd100.png)

Thanks!

**Comment by RosenZhu** [comment]
> Hello! Can you tell me how to retain the entire commit history? ![image](https://user-images.githubusercontent.com/49183837/145707401-8301c0c4-16c9-470b-8af4-bd80a2fbd100.png)
> 
> Thanks!

When `git clone` your project, just do **NOT** add the option `--depth 1`

**Comment by blu3sh0rk** [comment]
Got it,thank you!



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Xiaogang ***@***.***&gt;; 
发送时间: 2021年12月12日(星期天) 下午5:53
收件人: ***@***.***&gt;; 
抄送: ***@***.******@***.***&gt;; ***@***.***&gt;; 
主题: Re: [aflchurn/aflchurn] How can i retain the entire commit history? (Issue #1)





  
Hello! Can you tell me how to retain the entire commit history? 
 
Thanks!
  
When git clone your project, just do NOT add the option --depth 1
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
