### ISSUE TITLE
Could the aflchurn skip the determinisitic stage ?

### ISSUE THREAD

**Issue by ricardo-kcc** [aflchurn/aflchurn#2]
Could it skip the determinisitic stage by using `-d` ? Because part of experiment do that , such as fuzzbench.

**Comment by mboehme** [comment]
Yes. You should be able to use `-d`.

**Comment by ricardo-kcc** [comment]
Thanks. @mboehme .   Moreover， due to lack of git history information, it means the weight of every BB is equal if using vanilla afl-clang-fast to instrumentation.

**Comment by mboehme** [comment]
If there is no historical information, all BBs should get equal weight. Not sure if AFLChurn even throws an error.

**Comment by mboehme** [comment]
(Considering closed)
